// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY7HxDpAI_laNS4UkYSKTivOFQJcda-JI',
    appId: '1:380528866121:web:7395673ed759e81999e098',
    messagingSenderId: '380528866121',
    projectId: 'andriod-d6327',
    authDomain: 'andriod-d6327.firebaseapp.com',
    storageBucket: 'andriod-d6327.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1hvIonrRFGU7vzrkcKBHKI8zrdw0f8Y',
    appId: '1:380528866121:android:e15edc1f8978c6b499e098',
    messagingSenderId: '380528866121',
    projectId: 'andriod-d6327',
    storageBucket: 'andriod-d6327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV7LT_SghrTK0t062RxQCvMMKM_QKAY5E',
    appId: '1:380528866121:ios:686796fad38708bb99e098',
    messagingSenderId: '380528866121',
    projectId: 'andriod-d6327',
    storageBucket: 'andriod-d6327.firebasestorage.app',
    iosBundleId: 'com.example.mintfinder1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV7LT_SghrTK0t062RxQCvMMKM_QKAY5E',
    appId: '1:380528866121:ios:686796fad38708bb99e098',
    messagingSenderId: '380528866121',
    projectId: 'andriod-d6327',
    storageBucket: 'andriod-d6327.firebasestorage.app',
    iosBundleId: 'com.example.mintfinder1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY7HxDpAI_laNS4UkYSKTivOFQJcda-JI',
    appId: '1:380528866121:web:3886e3d6c0f80a2999e098',
    messagingSenderId: '380528866121',
    projectId: 'andriod-d6327',
    authDomain: 'andriod-d6327.firebaseapp.com',
    storageBucket: 'andriod-d6327.firebasestorage.app',
  );
}
